### ISSUE TITLE
Trueskill function fails on R v4.0.5

### ISSUE THREAD

**Issue by phoenixbh** [bhoung/trueskill-in-r#3]
The Trueskill function in Trueskill v0.2 fails on Rv4.0.5 with the following error:

```
Error in UseMethod("Trueskill") :
  no applicable method for 'Trueskill' applied to an object of class "list"

```
Even when using the simple example in the documentation:

```
Team1 <- Team("T1", rank = 1, list(Player("Alice", Gaussian(25, 8.3))))
Team2 <- Team("T1", rank = 2, list(Player("Bob", Gaussian(25, 8.3))))
teams <- list(Team1, Team2)

epsilon <- DrawMargin(draw_probability = 0.1, beta = 25 / 6, num_teams = 2)
parameters <- Parameters(beta = 25/6, epsilon, 25 / 300)

teams <- Trueskill(teams, parameters)
```

Reverting R back to v3.6.3 fixed the issue.

**Comment by Soccerama** [comment]
I have updated R to version 4.1.0 and the simple example above seems to not produce any errors.

**Comment by bhoung** [comment]
closing this, suggest going with R 4.1.0. thanks @phoenixbh & @Soccerama
